version: "3"

services:
  miniservice:
    volumes:
      - "./miniservice:/app"
      - "./minicore:/minicore"
    build:
      context: "./miniservice"      
    ports:
      - "5000:5000"
      - "5678:5678" # debug
    entrypoint: ./entrypoint.sh
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001" # RedisInsight
      - "6379:6379" # Redis

networks:
  default:
    name: scinet
    external: true
