version: "3"

services:
  miniservice:
    volumes:
      - "./service:/app"
    build:
      context: "./service"
      target: "development"
    ports:
      - "8080:8080"
      - "5678:5678" # debug
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001" # RedisInsight

networks:
  default:
    name: scinet
    external: true